name: "Code Analysis"
on: ["push", "pull_request"]

jobs:
  test:
    name: "Run Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'latest'
      - run: "go test ./..."
  golangci-lint:
    name: "Run GolangCI-Lint Code Analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'latest'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
